document.writeln("<footer id=\'footer\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("            <div class=\'footerbottom\'>");
document.writeln("                <div class=\'col-md-3 col-sm-6\'>");
document.writeln("                    <div class=\'footerwidget\'>");
document.writeln("                        <h4>");
document.writeln("                            新手帮助");
document.writeln("                        </h4>");
document.writeln("                        <div class=\'menu-course\'>");
document.writeln("                            <ul class=\'menu\'>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    什么是学贝？");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    称号怎么获取？");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    课程如何购买？");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    怎么充值？");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-md-3 col-sm-6\'>");
document.writeln("                    <div class=\'footerwidget\'>");
document.writeln("                        <h4>");
document.writeln("                            友情链接");
document.writeln("                        </h4>");
document.writeln("                        <div class=\'menu-course\'>");
document.writeln("                            <ul class=\'menu\'>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    扣丁学堂 </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    千锋教育");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    开放平台");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    学习联盟");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-md-3 col-sm-6\'>");
document.writeln("                    <div class=\'footerwidget\'>");
document.writeln("                        <h4>");
document.writeln("                            平台内容");
document.writeln("                        </h4>");
document.writeln("                        <div class=\'menu-course\'>");
document.writeln("                            <ul class=\'menu\'>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    视频专题");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    主流技术视频");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\'#\'>");
document.writeln("                                    视频评论");
document.writeln("                                </a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'#\'>");
document.writeln("                                        学习路线图");
document.writeln("                                    </a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <div class=\'col-md-3 col-sm-6\'>");
document.writeln("                    <div class=\'footerwidget\'>");
document.writeln("                        <h4>联系我们</h4>");
document.writeln("                        <p>有任何问题都可以及时反馈与我们</p>");
document.writeln("                        <div class=\'contact-info\'>");
document.writeln("                            <i class=\'fa fa-map-marker\'></i>&nbsp;郑州市二七区海为科技园<br>");
document.writeln("                            <i class=\'fa fa-phone\'></i>&nbsp;18515990152<br>");
document.writeln("                            <i class=\'fa fa-envelope-o\'></i>&nbsp;xingfei_work@163.com");
document.writeln("                        </div>");
document.writeln("                    </div><!-- end widget -->");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <!--CLEAR FLOATS-->");
document.writeln("    </div>");
document.writeln("    <div class=\'footer2\'>");
document.writeln("        <div class=\'container\'>");
document.writeln("            <div class=\'row\'>");
document.writeln("                <div class=\'col-md-12 panel\' style=\'text-align: center\'>");
document.writeln("                    <p>");
document.writeln("                        Copyright © 2015-2019 SelfCoding. All Rights Reserved.");
document.writeln("                    </p>");
document.writeln("                    <p>");
document.writeln("                        SelfCoding专注于学习平台的打造，希望更多的人前来学习 <a href=\'http://www.miitbeian.gov.cn/state\'>豫ICP备19001906号</a>");
document.writeln("                    </p>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</footer>");