document.writeln("<div class=\'navbar navbar-inverse\' style='border-bottom: 1px solid gray'>");
document.writeln("    <div class=\'container\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("            <!-- Button for smallest screens -->");
document.writeln("            <a class=\'navbar-brand\' href=\'index.html\'>");
document.writeln("                <img src=\'media/images/logo.JPG\' alt=\'Techro HTML5 template\' height=\'44px\'></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'navbar-header\' style=\'text-align: center;margin-left: 10%;width: 30%;\'>");
document.writeln("            <div class=\'input-group\'>");
document.writeln("                <input type=\'text\' class=\'form-control input-lg\'><span");
document.writeln("                    class=\'input-group-addon btn btn-primary\'>搜索</span>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <div class=\'navbar-collapse collapse\'>");
document.writeln("            <ul class=\'nav navbar-nav pull-right mainNav\'>");
document.writeln("                <li class=\'c1 active\'><a href=\'index.html\'>主页</a></li>");
document.writeln("                <li class=\'c2\'><a href=\'courses.html\'>视频</a></li>");
document.writeln("                <li class=\'c5\'><a href=\'interview.html\'>面试宝典</a></li>");
document.writeln("                <li class=\'c6 dropdown\'>");
document.writeln("                    <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\'>我的<b class=\'caret\'></b></a>");
document.writeln("                    <ul class=\'dropdown-menu\'>");
document.writeln("                        <li><a href=\'sidebar-right.html\'>我的钱包</a></li>");
document.writeln("                        <li><a href=\'#\'>我的课程</a></li>");
document.writeln("                        <li><a href=\'#\'>学习记录</a></li>");
document.writeln("                        <li><a href=\'#\'>我的资料</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\'c7\'><a href=\'contact.html\'>联系我们</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");